<?
use angelrove\utils\Vendor;

// Basics ---------------------


// Other -------------------------
Vendor::conf('font-awesome-iconate',
   'https://cdnjs.cloudflare.com/ajax/libs/iconate/0.2.7/', array(
         'iconate.min.css',
         'iconate.min.js',
));

Vendor::conf('isotope',
   '//cdnjs.cloudflare.com/ajax/libs/', array(
         'jquery.isotope/3.0.1/isotope.pkgd.min.js',
         'jquery.imagesloaded/4.1.0/imagesloaded.min.js'
));
