#!/usr/bin/env php
<?php

require __DIR__.'/../vendor/autoload.php';

/**
 * Magic commands
 */

use angelrove\membrillo2\Magic\Magic;

$longopts = array(
    "newsecc:",
);
$params = getopt('', $longopts);

// Run the Magic command
Magic::command(__DIR__, $params);