<?php
use angelrove\utils\Vendor;

// Bootstrap theme (overwriting default) ---------------------
// Vendor::conf('bootstrap',
//    '//cdnjs.cloudflare.com/ajax/libs/', array(
//          'twitter-bootstrap/3.3.7/js/bootstrap.min.js',
//          'bootswatch/3.3.7/yeti/bootstrap.min.css',
// ));


// Other -------------------------
// Vendor::conf('font-awesome-iconate',
//    'https://cdnjs.cloudflare.com/ajax/libs/iconate/0.2.7/', array(
//          'iconate.min.css',
//          'iconate.min.js',
// ));

// Vendor::conf('isotope',
//    '//cdnjs.cloudflare.com/ajax/libs/', array(
//          'jquery.isotope/3.0.1/isotope.pkgd.min.js',
//          'jquery.imagesloaded/4.1.0/imagesloaded.min.js'
// ));

// Vendor::conf('bootstrap-calendar',
//    '//cdnjs.cloudflare.com/ajax/libs/', array(
//          'underscore.js/1.8.3/underscore-min.js',
//          'bootstrap-calendar/0.2.5/js/calendar.min.js',
//          'bootstrap-calendar/0.2.5/js/language/es-ES.min.js',
//          'bootstrap-calendar/0.2.5/css/calendar.min.css',
// ));
