#!/usr/bin/env php
<?php
/**
 * magic
 *
 * @author José A. Romero Vegas <jangel.romero@gmail.com>
 *
 * Sample: php magic --newsecc notas
 *
 * Commands:
 *   newsecc
 *      detail
 *   newmodel
 */

require __DIR__.'/../vendor/autoload.php';

$longopts = array(
    "newsecc:",
    "parentdetail:",
    "newmodel:",

    "param:",
);
$params = getopt('', $longopts);

// Run the Magic command
$magic = new angelrove\membrillo\Magic\Magic(__DIR__);
$magic->command($params);
