<?
// WApplication -------------------------------------------
require_once('_libs/WApplication/WApplication.inc');

// WInputs ------------------------------------------------
use angelrove\membrillo\WInputs\WInputRadios\WInputRadios;
use angelrove\membrillo\WInputs\WInputCheck\WInputCheck;
use angelrove\membrillo\WInputs\WInputHtml2\WInputHtml2;

$wInputRadios = new WInputRadios();
$wInputCheck  = new WInputCheck();
$wInputHtml2  = new WInputHtml2();
